---
title: "Plots"
author: "Alex Wood"
date: "January 14, 2019"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(corrplot)
```

#bring in the data
```{r}

aqariusReady <- read_csv("aqariusReady.csv", 
    col_types = cols(`Air Temp (C)` = col_skip(), 
        D_Ex = col_double(), Date = col_date(format = "%m/%d/%Y"), 
        Time = col_skip(), orp = col_double()))


allSites=as.data.frame(aqariusReady)

```

#see some thangs

```{r}
plot(allSites)

allsitesNdate=allSites[-2]
allsitesNdate=allsitesNdate[-1]
allsitesNdate

#carefull with the usage of pairwise.complete or pairwise.complete.obs..these don't work that well
q=cor(allsitesNdate, use = "complete")
corrplot.mixed(q)


```
#graphs

#isotopes

```{r}
ggplot(allSites, aes(x=allSites$D,y=allSites$O18, color=Season))+geom_point(size=3,shape=17 )+theme_bw()+stat_summary(fun.data=mean_cl_normal) + 
  geom_smooth(method='lm',formula=y~x)



xdensity <- ggplot(allSites, aes(allSites$O18, fill=Season)) + 
  geom_density(alpha=.5) + theme(legend.position = "none")+scale_color_brewer(palette="Dark2")
xdensity
```

#discharge
```{r}

dim(allSites)
ggplot(allSites, aes(x=allSites$Date, y=allSites$cms, color=Site, group=Site))+geom_line(data=allSites[!is.na(allSites$cms),],aes(x=allSites$Date, y=allSites$cms), linetype=2)+geom_point(shape=18, size=5)+scale_y_log10()+scale_x_date(date_breaks = "months" , date_labels = "%b-%y")+ggtitle("Hand Measured Discharge at GRCA C aquifer Springs")+xlab(NULL)+ylab("Discharge (L/s)")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=11, face="bold", color="black"))

```

#isotope temporal
```{r}
ggplot(allSites, aes(x=Date, y=allSites$O18, color=Site, group=Site))+geom_line(data=allSites[!is.na(allSites$Date),],aes(x=Date, y=O18), linetype=2)+geom_point(shape=18, size=5)+scale_y_log10()+scale_x_date(date_breaks = "months" , date_labels = "%b-%y")+ggtitle("Hand Measured Discharge at GRCA C aquifer Springs")+xlab(NULL)+ylab("Discharge (L/s)")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=11, face="bold", color="black"))
```


#cation/anion
```{r}
ggplot(allSites, aes(x=Date, y=allSites$Na, color=Site, group=Site))+geom_line(data=allSites[!is.na(allSites$Date),],aes(x=Date, y=Na), linetype=2)+geom_point(shape=18, size=5)+scale_y_log10()+scale_x_date(date_breaks = "months" , date_labels = "%b-%y")+ggtitle("Hand Measured Discharge at GRCA C aquifer Springs")+xlab(NULL)+ylab("Discharge (L/s)")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=11, face="bold", color="black"))
```





